package generate

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// realRandomPassword is the verbatim nivis gen v0.4.0 output for
// random.random_password — a required arg, many optional args, computed outputs.
const realRandomPassword = `# Generated by tn-gen for random.random_password — do not edit by hand.
# Computed outputs (read via the resource's refAttr): bcrypt_hash, id, result
{ nivis }:
{ name, keepers ? null, length ? null, lower ? null, min_lower ? null, min_numeric ? null, min_special ? null, min_upper ? null, number ? null, numeric ? null, override_special ? null, special ? null, upper ? null, overrides ? {} }:
let
  _length = if length == null then throw "random.random_password: required argument 'length' is missing" else length;
  config =
    { length = _length; }
    // (if keepers == null then {} else { keepers = keepers; })
    // (if lower == null then {} else { lower = lower; })
    ;
in
nivis.mkResource ({ provider = "random"; type = "random_password"; inherit name config; } // overrides)
`

func TestContractPath(t *testing.T) {
	got := ContractPath("hashicorp", "random", "3.9.0")
	want := filepath.Join("registry", "docs", "providers", "hashicorp", "random", "3.9.0", "index.json")
	if got != want {
		t.Errorf("ContractPath = %q, want %q", got, want)
	}
}

// TestParseConstructor parses the real random_password output and checks the
// required/optional/computed split is correct.
func TestParseConstructor(t *testing.T) {
	c := ParseConstructor(realRandomPassword)
	if c.Provider != "random" || c.Type != "random_password" {
		t.Errorf("provider/type = %q/%q, want random/random_password", c.Provider, c.Type)
	}
	if len(c.Required) != 1 || c.Required[0] != "length" {
		t.Errorf("Required = %v, want [length]", c.Required)
	}
	for _, a := range c.Optional {
		if a == "name" || a == "overrides" || a == "length" {
			t.Errorf("Optional must not include %q", a)
		}
	}
	if !contains(c.Optional, "keepers") || !contains(c.Optional, "lower") {
		t.Errorf("Optional = %v, want it to include keepers and lower", c.Optional)
	}
	wantComputed := []string{"bcrypt_hash", "id", "result"}
	if strings.Join(c.Computed, ",") != strings.Join(wantComputed, ",") {
		t.Errorf("Computed = %v, want %v", c.Computed, wantComputed)
	}
}

// TestRenderDocIsNixNotHCL is the nix-rendering spec scenario: the doc shows the
// Nix constructor signature + outputs and contains NO HCL `resource {}` block.
func TestRenderDocIsNixNotHCL(t *testing.T) {
	c := ParseConstructor(realRandomPassword)
	doc := RenderDoc(c)

	if ContainsHCLResourceBlock(doc) {
		t.Error("rendered doc must NOT contain an HCL resource block")
	}
	if !strings.Contains(doc, "```nix") {
		t.Error("rendered doc must contain a Nix code block")
	}
	if !strings.Contains(doc, "length") {
		t.Error("doc must show the required `length` argument")
	}
	if !strings.Contains(doc, "overrides ? {}") {
		t.Error("doc signature must include overrides ? {}")
	}
	if !strings.Contains(doc, "refAttr") || !strings.Contains(doc, "result") {
		t.Error("doc must list computed outputs (e.g. result) read via refAttr")
	}
	if strings.Contains(doc, "resource \"random_password\"") {
		t.Error("doc must not contain an HCL resource declaration")
	}
}

// writeFixtureProvider lays out an extraction-output tree for one provider
// version with the given constructors, mimicking tools/extract.
func writeFixtureProvider(t *testing.T, root, ns, name, version string, protocols []string, platforms [][2]string, constructors map[string]string) string {
	t.Helper()
	vdir := filepath.Join(root, ns, name, version)
	idDir := filepath.Join(vdir, name)
	if err := os.MkdirAll(idDir, 0o755); err != nil {
		t.Fatal(err)
	}
	for typ, body := range constructors {
		if err := os.WriteFile(filepath.Join(idDir, typ+".nix"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	var plats []map[string]string
	for _, p := range platforms {
		plats = append(plats, map[string]string{"os": p[0], "arch": p[1]})
	}
	meta := map[string]any{
		"address":   ns + "/" + name,
		"namespace": ns,
		"name":      name,
		"version":   version,
		"protocols": protocols,
		"platforms": plats,
	}
	mb, _ := json.MarshalIndent(meta, "", "  ")
	if err := os.WriteFile(filepath.Join(vdir, "metadata.json"), mb, 0o644); err != nil {
		t.Fatal(err)
	}
	return vdir
}

// TestGenerateProviderContract is the docs-contract spec scenario: index lists
// every item, each item has a document, and the compat badge is present.
func TestGenerateProviderContract(t *testing.T) {
	extractRoot := t.TempDir()
	contractRoot := t.TempDir()
	vdir := writeFixtureProvider(t, extractRoot, "hashicorp", "random", "3.9.0",
		[]string{"5.0"},
		[][2]string{{"linux", "amd64"}, {"linux", "arm64"}, {"darwin", "arm64"}},
		map[string]string{
			"random_password": realRandomPassword,
			"random_id": `# Generated by tn-gen for random.random_id — do not edit by hand.
# Computed outputs (read via the resource's refAttr): b64_std, dec, hex, id
{ nivis }:
{ name, byte_length ? null, keepers ? null, overrides ? {} }:
let
  _byte_length = if byte_length == null then throw "random.random_id: required argument 'byte_length' is missing" else byte_length;
  config = { byte_length = _byte_length; };
in
nivis.mkResource ({ provider = "random"; type = "random_id"; inherit name config; } // overrides)
`,
		})

	idxPath, err := GenerateProvider(vdir, contractRoot)
	if err != nil {
		t.Fatalf("GenerateProvider: %v", err)
	}

	var pv ProviderVersion
	readJSON(t, idxPath, &pv)
	if pv.ID != "3.9.0" {
		t.Errorf("version = %q, want 3.9.0", pv.ID)
	}
	if len(pv.Docs.Resources) != 2 {
		t.Fatalf("expected 2 resources, got %d", len(pv.Docs.Resources))
	}
	if pv.Docs.Datasources == nil || pv.Docs.Functions == nil || pv.Docs.Guides == nil {
		t.Error("docs lists must be present (empty, not null)")
	}

	outDir := filepath.Dir(idxPath)
	for _, item := range pv.Docs.Resources {
		docPath := filepath.Join(outDir, item.Name+".md")
		body, rerr := os.ReadFile(docPath)
		if rerr != nil {
			t.Errorf("missing document for %q: %v", item.Name, rerr)
			continue
		}
		if ContainsHCLResourceBlock(string(body)) {
			t.Errorf("document for %q contains an HCL resource block", item.Name)
		}
	}

	if pv.Compat.Tier != "compatible by design" {
		t.Errorf("compat tier = %q, want 'compatible by design'", pv.Compat.Tier)
	}
	if !pv.Compat.SchemaExtractable {
		t.Error("schema_extractable should be true (we have constructors)")
	}
	if len(pv.Compat.Protocols) != 1 || pv.Compat.Protocols[0] != "5.0" {
		t.Errorf("compat protocols = %v, want [5.0]", pv.Compat.Protocols)
	}
	wantArches := "linux/amd64,linux/arm64,darwin/arm64"
	if strings.Join(pv.Compat.Architectures, ",") != wantArches {
		t.Errorf("compat arches = %v, want %s", pv.Compat.Architectures, wantArches)
	}
}

// TestRegenerationReflectsSchemaChange is the nix-rendering spec scenario:
// regenerating across versions reflects the new attributes/outputs.
func TestRegenerationReflectsSchemaChange(t *testing.T) {
	extractRoot := t.TempDir()
	contractRoot := t.TempDir()

	v1body := `# Generated by tn-gen for acme.acme_thing — do not edit by hand.
# Computed outputs (read via the resource's refAttr): id
{ nivis }:
{ name, foo ? null, overrides ? {} }:
nivis.mkResource ({ provider = "acme"; type = "acme_thing"; inherit name config; } // overrides)
`
	v1dir := writeFixtureProvider(t, extractRoot, "acme", "thing", "1.0.0", []string{"6.0"}, nil,
		map[string]string{"acme_thing": v1body})
	idx1, err := GenerateProvider(v1dir, contractRoot)
	if err != nil {
		t.Fatal(err)
	}
	doc1, _ := os.ReadFile(filepath.Join(filepath.Dir(idx1), "acme_thing.md"))
	if strings.Contains(string(doc1), "bar") {
		t.Error("v1 doc should not mention the v2-only arg `bar`")
	}

	v2body := `# Generated by tn-gen for acme.acme_thing — do not edit by hand.
# Computed outputs (read via the resource's refAttr): arn, id
{ nivis }:
{ name, foo ? null, bar ? null, overrides ? {} }:
let
  _bar = if bar == null then throw "acme.acme_thing: required argument 'bar' is missing" else bar;
in
nivis.mkResource ({ provider = "acme"; type = "acme_thing"; inherit name config; } // overrides)
`
	v2dir := writeFixtureProvider(t, extractRoot, "acme", "thing", "2.0.0", []string{"6.0"}, nil,
		map[string]string{"acme_thing": v2body})
	idx2, err := GenerateProvider(v2dir, contractRoot)
	if err != nil {
		t.Fatal(err)
	}
	doc2, _ := os.ReadFile(filepath.Join(filepath.Dir(idx2), "acme_thing.md"))
	if !strings.Contains(string(doc2), "bar") {
		t.Error("v2 doc must reflect the new required arg `bar`")
	}
	if !strings.Contains(string(doc2), "arn") {
		t.Error("v2 doc must reflect the new computed output `arn`")
	}
	if string(doc1) == string(doc2) {
		t.Error("regenerated docs must differ across versions")
	}
}

// TestGenerateAllResilient generates a whole extraction tree and ignores a
// version dir with no metadata.json.
func TestGenerateAllResilient(t *testing.T) {
	extractRoot := t.TempDir()
	contractRoot := t.TempDir()
	writeFixtureProvider(t, extractRoot, "hashicorp", "null", "3.3.0", []string{"5.0"}, nil,
		map[string]string{"null_resource": `# Generated by tn-gen for null.null_resource — do not edit by hand.
# Computed outputs (read via the resource's refAttr): id
{ nivis }:
{ name, triggers ? null, overrides ? {} }:
nivis.mkResource ({ provider = "null"; type = "null_resource"; inherit name config; } // overrides)
`})
	_ = os.MkdirAll(filepath.Join(extractRoot, "junk"), 0o755)

	idxs, err := GenerateAll(extractRoot, contractRoot, func(f string, a ...interface{}) {})
	if err != nil {
		t.Fatal(err)
	}
	if len(idxs) != 1 {
		t.Errorf("expected 1 generated provider, got %d", len(idxs))
	}
}

// TestGenerateDatasourceOnlyProvider covers a provider with NO resource
// constructors (e.g. hashicorp/http, hashicorp/external — datasource-only).
// nivis gen emits no .nix; the provider is still schema-extractable and must
// appear in the contract with an empty resource list.
func TestGenerateDatasourceOnlyProvider(t *testing.T) {
	extractRoot := t.TempDir()
	contractRoot := t.TempDir()
	// No constructors — just metadata, as a successful extract of a datasource-
	// only provider produces.
	vdir := writeFixtureProvider(t, extractRoot, "hashicorp", "http", "3.6.0",
		[]string{"5.0"}, [][2]string{{"linux", "amd64"}}, map[string]string{})

	idxPath, err := GenerateProvider(vdir, contractRoot)
	if err != nil {
		t.Fatalf("GenerateProvider: %v", err)
	}
	var pv ProviderVersion
	readJSON(t, idxPath, &pv)
	if len(pv.Docs.Resources) != 0 {
		t.Errorf("expected 0 resources, got %d", len(pv.Docs.Resources))
	}
	// The schema WAS extracted (we have metadata) — must not be reported as
	// not-extractable just because there are no resources.
	if !pv.Compat.SchemaExtractable {
		t.Error("a datasource-only provider is still schema_extractable")
	}
}

func contains(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}

func readJSON(t *testing.T, path string, dst any) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(b, dst); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
}
