package generate

import (
	"bufio"
	"strings"
)

// Constructor is the parsed model of one `nivis gen` .nix file. It captures the
// surface the renderer needs: the provider/type identity, the constructor's
// required and optional arguments, and the computed outputs (read via refAttr).
//
// The .nix shape this parses (verified against nivis gen v0.4.0):
//
//	# Generated by tn-gen for <provider>.<type> — do not edit by hand.
//	# Computed outputs (read via the resource's refAttr): <a, b, c>
//	{ nivis }:
//	{ name, opt ? null, ..., overrides ? {} }:
//	let
//	  _req = if req == null then throw "<provider>.<type>: required argument 'req' is missing" else req;
//	  config = { req = _req; } // (if opt == null then {} else { opt = opt; }) ... ;
//	in
//	nivis.mkResource ({ provider = "<provider>"; type = "<type>"; inherit name config; } // overrides)
type Constructor struct {
	Provider string   // e.g. "random"
	Type     string   // e.g. "random_password"
	Required []string // required arguments (have a throw-guard), in declared order
	Optional []string // optional arguments (? null), in declared order
	Computed []string // computed outputs, from the header comment
}

// AllArgs returns required then optional arguments — the constructor's user
// inputs, excluding the implicit `name` and `overrides`.
func (c Constructor) AllArgs() []string {
	out := make([]string, 0, len(c.Required)+len(c.Optional))
	out = append(out, c.Required...)
	out = append(out, c.Optional...)
	return out
}

// ParseConstructor parses a nivis gen .nix constructor file body into a
// Constructor. It is deliberately tolerant: a field it cannot find is left
// empty rather than failing, so a future nivis gen tweak degrades gracefully.
func ParseConstructor(body string) Constructor {
	var c Constructor
	requiredSet := map[string]bool{}

	sc := bufio.NewScanner(strings.NewReader(body))
	sc.Buffer(make([]byte, 0, 1024*1024), 1024*1024) // tolerate long lines
	var lambdaArgs []string
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch {
		case strings.HasPrefix(line, "# Computed outputs"):
			c.Computed = parseComputed(line)
		case isLambdaArgLine(line) && lambdaArgs == nil:
			lambdaArgs = parseLambdaArgs(line)
		case strings.Contains(line, "required argument '"):
			if name := parseRequiredName(line); name != "" {
				requiredSet[name] = true
			}
		case strings.Contains(line, "nivis.mkResource"):
			c.Provider, c.Type = parseProviderType(line)
		}
	}

	// Split the lambda args into required/optional, preserving declared order,
	// dropping the implicit name/overrides.
	for _, a := range lambdaArgs {
		if a == "name" || a == "overrides" {
			continue
		}
		if requiredSet[a] {
			c.Required = append(c.Required, a)
		} else {
			c.Optional = append(c.Optional, a)
		}
	}
	return c
}

// parseComputed extracts the comma-separated outputs from the header line
// "# Computed outputs (read via the resource's refAttr): a, b, c".
func parseComputed(line string) []string {
	idx := strings.LastIndex(line, ":")
	if idx < 0 {
		return nil
	}
	var out []string
	for _, p := range strings.Split(line[idx+1:], ",") {
		if s := strings.TrimSpace(p); s != "" {
			out = append(out, s)
		}
	}
	return out
}

// isLambdaArgLine reports whether a line is the constructor argument lambda:
// a brace-delimited arg set ending in a colon that mentions name and overrides.
func isLambdaArgLine(line string) bool {
	return strings.HasPrefix(line, "{") && strings.HasSuffix(line, ":") &&
		strings.Contains(line, "name") && strings.Contains(line, "overrides")
}

// parseLambdaArgs extracts argument names from "{ name, a ? null, ..., overrides ? {} }:".
func parseLambdaArgs(line string) []string {
	line = strings.TrimSuffix(line, ":")
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "{")
	line = strings.TrimSuffix(line, "}")
	var args []string
	for _, part := range strings.Split(line, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		// "a ? null" or "overrides ? {}" or "name" -> take the leading token.
		name := part
		if i := strings.IndexAny(part, " ?"); i >= 0 {
			name = part[:i]
		}
		if name != "" {
			args = append(args, name)
		}
	}
	return args
}

// parseRequiredName extracts X from `... throw "...: required argument 'X' is missing" ...`.
func parseRequiredName(line string) string {
	const marker = "required argument '"
	i := strings.Index(line, marker)
	if i < 0 {
		return ""
	}
	rest := line[i+len(marker):]
	j := strings.IndexByte(rest, '\'')
	if j < 0 {
		return ""
	}
	return rest[:j]
}

// parseProviderType extracts provider and type from the mkResource line:
// `nivis.mkResource ({ provider = "random"; type = "random_password"; ... })`.
func parseProviderType(line string) (provider, typ string) {
	provider = extractQuotedAfter(line, "provider = ")
	typ = extractQuotedAfter(line, "type = ")
	return provider, typ
}

// extractQuotedAfter finds `key"VALUE"` and returns VALUE.
func extractQuotedAfter(line, key string) string {
	i := strings.Index(line, key)
	if i < 0 {
		return ""
	}
	rest := line[i+len(key):]
	start := strings.IndexByte(rest, '"')
	if start < 0 {
		return ""
	}
	rest = rest[start+1:]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	return rest[:end]
}
